### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by robrecord** [exalted/sublimetext-launcher#1]
Hi there,

I can't get this to work, nor the other two apps that are supposed to do the same.

I renamed my Sublime Text 3.app to Sublime Text.app

I linked my subl to /usr/bin/local/subl

I can use subl fine from the command line.

I modified your app's python code to use /usr/bin/local/subl instead of Sublime Text 2.

when I do /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/Support/lsregister -dump | grep -B6 bindings:.*subl:

I get 3 entries (because of other apps I tried).

Checking with the DefaultRC preference pane, I can see the your app is set to be the default handler for subl:// links.

Any ideas I can try?
How can I get debug output from the python script to see what it's doing? I've never used python before.

Thanks in advance!

**Comment by robrecord** [comment]
I have the URL scheme set correctly:
In xdebug it is xdebug.file_link_format="subl://open/?url=file://%f&line=%l"
which creates (for example): subl://open/?url=file:///Users/robrecord/Sites/migrate_database_119-125/Migrate.class.php&line=200

I have been trying to test by creating my own applescript app that responds to an "on open location" and even that does nothing.

Do you think it's something to do with sandboxing?

**Comment by exalted** [comment]
> I renamed my Sublime Text 3.app to Sublime Text.app

I have no idea if this still would work with the third version (i.e., `Sublime Text 3.app`), because I am still using the second version and I have no plans to upgrade soon–ish.

> I linked my subl to /usr/bin/local/subl

My solution doesn't even look at your "shortcuts", infact currently it is hardcoded [this way](https://github.com/exalted/sublimetext-launcher/blob/master/Sublime%20Text%202%20Launcher.app/Contents/Resources/Scripts/subl-launcher.py#L12). Feel free to try to change that and see if it works (and please let me know).

> when I do /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/Support/lsregister -dump | grep -B6 bindings:.*subl:
> 
> I get 3 entries (because of other apps I tried).
> 
> Checking with the DefaultRC preference pane, I can see the your app is set to be the default handler for subl:// links.

Oh, I didn't know about RCDefaultApp, cool! :wink: You could try to "fix things" (as per the README):

``` bash
/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/Support/lsregister -kill -r -domain local -domain system -domain user
```

... this should clear all custom URL schemes, and if you open `Sublime Text 2 Launcher.app` once (it will quickly quit itself, this is the expected behaviour), now you should have only one application — this one — registered for `subl` scheme.

**Comment by exalted** [comment]
> Do you think it's something to do with sandboxing?

I have no idea, sorry.

**Comment by robrecord** [comment]
> I have no idea if this still would work with the third version (i.e., Sublime Text 3.app)

I reinstalled Sublime Text 2 and it still didn't work. I have renamed my ST3 back to its proper name too.

I actually already hacked your python to use a different path - I just re-downloaded the original from this repo and tried it - once without modification & once changing the "2" to a "3" in the app path name.

> `/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/Support/lsregister -kill -r -domain local -domain system -domain user`

Tried it a few times now. Anything left on my system shows up as a service still, which is fine, and I can switch using RCDefaultApp (it's great isn't it!)

Oh well :) I think something on my system is buggered, seeing as it works for everyone else. Maybe the Sublime dev will build it into his app. Thanks for trying to helo!

**Comment by exalted** [comment]
You could try to do some prints here and there in that python script (it's only four lines after all) to see if something breaks...

**Comment by robrecord** [comment]
I tried doing some 'display dialog's in the applescript inside the "on open location" part and it didn't do anything. I also put a display dialog before that part, and when run normally it does output - but when using in the proper way it doesn't. It's as if it's never being called. Unfortunately I don't know how to get the output of a python print statement; since it's being called from applescript and not the CLI, I won't see it - is that correct?

**Comment by exalted** [comment]
I am not an AppleScript expert, but what I noticed (when I was dealing with this issue on my own) is that `on open location` block won’t be executed if it’s not triggered by the URL scheme, therefore try this:

``` applescript
on open location receivedURL
    display dialog "Hello!"
end open location
```

This should display the dialog just fine when you try to go to `subl://anything` URL **in Safari** (for some reason if you’d try the same with `open "subl://anything"` from `Terminal.app`, it shouldn’t work.

Now, try this one instead:

``` applescript
on open location receivedURL
    display dialog receivedURL
end open location
```

This should display the dialog with the received URL just fine. If you’re not getting even there, please let me know.

**Comment by robrecord** [comment]
Cheers for the suggestion - I had made my own little application to do just as you suggested, and it didn't work...

BUT - I just now used TinkerTool System to remove all my caches across the whole system, as well as a few other maintenance tasks, and now it works :) IT WORKS! :D/

Thanks for your willingness to help! And thank you for writing this app :)

**Comment by exalted** [comment]
:sparkles:
